import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import { Directory, File, Paths } from 'expo-file-system';
import { absolute, type PhraseKey } from './api';
import { getKV } from './db';

/**
 * Only the companion's own voice (ElevenLabs audio generated by the server) is ever played.
 * There is deliberately no system text-to-speech fallback: a different, robotic voice would confuse the person.
 * When no audio is available the screens show the text and vibrate instead.
 */

let current: AudioPlayer | null = null;

export function stopPlayback() {
  current?.remove();
  current = null;
}

/** Plays a local file or remote URL. */
export async function playUri(uri: string) {
  stopPlayback();
  await setAudioModeAsync({ playsInSilentMode: true, allowsRecording: false });
  current = createAudioPlayer({ uri });
  current.play();
}

export type CachedPhrases = Partial<Record<PhraseKey, { text: string; path: string | null }>>;

export const cachedPhrases = () => getKV<CachedPhrases>('phrases', {});

/** Plays a fixed line (well done, reminder in 10 min...) in the companion's voice. Silent if not cached. */
export async function playPhrase(key: PhraseKey) {
  const path = (await cachedPhrases())[key]?.path;
  if (path) await playUri(path).catch(() => undefined);
}

const audioDir = () => new Directory(Paths.document, 'voice');

/** Downloads a server audio file so it plays offline later. Returns the local uri. */
export async function cacheAudio(audioUrl: string): Promise<string | null> {
  try {
    const dir = audioDir();
    if (!dir.exists) dir.create();
    const file = await File.downloadFileAsync(absolute(audioUrl), dir, { idempotent: true });
    return file.uri;
  } catch {
    return null;
  }
}
